### ISSUE TITLE
BranchError.ERR_BRANCH_DUPLICATE_URL

### ISSUE THREAD

**Issue by AdamGrzybkowski** [BranchMetrics/android-branch-deep-linking-attribution#701]
Recently I've been getting more and more of this error `BranchError.ERR_BRANCH_DUPLICATE_URL`. 
Could you guys help me understand why this is happening? 
Why in such case the long URL is not returned?

**Comment by code-crusher** [comment]
Hey @AdamGrzybkowski - So it seems you are using `alias` in the Branch link to make them more personalized. As these `aliases` are unique per link, if you try to use the same `alias` to create a new link which has a different link data than the original link, then we would reject that link creation call. This can include changing any analytics label, link properties etc.

So, once you create a link with `alias`, that alias now is the identifier for a particular link data, which is not editable. You can also refer our docs here: https://docs.branch.io/links/quick-links/ 

Using a new alias or using the same properties for the same alias should fix the issue.

**Comment by AdamGrzybkowski** [comment]
Thanks, @code-crusher for your answer. I'm not sure I follow tough...

I do create a deep link using Branch SDK. I set one additional data and a tag. 
The additional data cannot be changed per user and the tag was not changed yet to(it could but it is the same now for all users) So the alias should be still the same? 

I was trying to reproduce this with no luck, but I do see this in my crashlytic service.

**Comment by AdamGrzybkowski** [comment]
@code-crusher ^ ?

**Comment by code-crusher** [comment]
Hey @AdamGrzybkowski - can you share the code snippet you use to generate the Branch link? If you are using an alias, then this issue can come in accidentally too if the alias used is the same and some other value gets changed in the data while generating the link. 

What you can choose to do is if this fails at any point in production(by reading `BranchError error`), you can choose to create a new link without the alias in that case to prevent the app crashing and to have a link no matter the case.

**Comment by AdamGrzybkowski** [comment]
@code-crusher 
yeah sure, here is the code. Maybe I'm doing sth wrong with `BranchUniversalObject`? 
```kotlin
val branchUniversalObject = BranchUniversalObject()
                .setCanonicalIdentifier("some_unique_user_id")
                .setLocalIndexMode(BranchUniversalObject.CONTENT_INDEX_MODE.PUBLIC)

val linkProperties = LinkProperties()
                .addTag("some_tag") // this tag was not changed
                .addControlParameter("user_id_key", "some_unique_user_id")

branchUniversalObject.generateShortUrl(context, linkProperties) { url, error ->
                if (error != null) {
                    Log.e("TAG", "MSG", Exception(error.message))
                }
                //do sth with the URL
}
```

Interesting thing is that I had a really big spike with such error only in one day. Now it calmed down

**Comment by AdamGrzybkowski** [comment]
@code-crusher could you look at the code above ^ ?

**Comment by AdamGrzybkowski** [comment]
@code-crusher ?

**Comment by csalmi-branch** [comment]
@AdamGrzybkowski reading through your previous comments, it sounds like you encountered this issue on one day? Is that correct? Are you still running into this error?

**Comment by AdamGrzybkowski** [comment]
That day there was quite a big spike of these errors. I see this error in crashlytics but I couldn't reproduce it myself.

**Comment by csalmi-branch** [comment]
Have you seen these errors since? We haven't been able to re-produce this internally, which makes it much harder to figure out if something was misconfigured or if there is a bug.

**Comment by echo-branch** [comment]
closing due to inactivity
