### ISSUE TITLE
Crash after updating to 5.0.10 and above

### ISSUE THREAD

**Issue by mihaicristianpetrescu** [BranchMetrics/android-branch-deep-linking-attribution#953]
After upgrading from 5.0.9 to 5.0.10 or above we started seeing a constant crash when opening the app, placing it in background and then resuming it from the multitask browser:

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.content.Intent.getParcelableExtra(java.lang.String)' on a null object reference
>         at android.app.Activity.getReferrer(Activity.java:6279)
>         at androidx.core.app.ActivityCompat.getReferrer(ActivityCompat.java:335)
>         at io.branch.referral.Branch$InitSessionBuilder.init(Branch.java:3062)
>         at io.branch.referral.BranchActivityLifecycleObserver.onActivityResumed(BranchActivityLifecycleObserver.java:73)
>         at android.app.Application.dispatchActivityResumed(Application.java:416)
>         at android.app.Activity.dispatchActivityResumed(Activity.java:1397)
>         at android.app.Activity.onResume(Activity.java:1950)
>         at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:410)

This crash is coming out of the referral support implementation, check the code below from the init() method of Branch.jaca class:

> Activity activity = branch.getCurrentActivity();
>             Intent intent = activity != null ? activity.getIntent() : null;
> 
>             if (activity != null && ActivityCompat.getReferrer(activity) != null) {
>                 PrefHelper.getInstance(activity).setInitialReferrer(ActivityCompat.getReferrer(activity).toString());
>             }

The problem here is that `ActivityCompat.getReferrer(activity)` is actually trying to get a parcelableExtra from within the Intent of the Activity, but if the Intent of the Activity is null, then this crashes, 100% of the time.

From ActivityCompat class:

>     @Nullable
>     public static Uri getReferrer(@NonNull Activity activity) {
>         if (Build.VERSION.SDK_INT >= 22) {
>             return activity.getReferrer();
>         }
>         Intent intent = activity.getIntent();
>         Uri referrer = intent.getParcelableExtra("android.intent.extra.REFERRER");
>         if (referrer != null) {
>             return referrer;
>         }
>         String referrerName = intent.getStringExtra("android.intent.extra.REFERRER_NAME");
>         if (referrerName != null) {
>             return Uri.parse(referrerName);
>         }
>         return null;
>     }

Activity.getReferrer does the following:

> public Uri getReferrer() {
>         Intent intent = getIntent();
>         try {
>             Uri referrer = intent.getParcelableExtra(Intent.EXTRA_REFERRER);
>             if (referrer != null) {
>                 return referrer;
>             }
>             String referrerName = intent.getStringExtra(Intent.EXTRA_REFERRER_NAME);
>             if (referrerName != null) {
>                 return Uri.parse(referrerName);
>             }
>         } catch (BadParcelableException e) {
>             Log.w(TAG, "Cannot read referrer from intent;"
>                     + " intent extras contain unknown custom Parcelable objects");
>         }
>         if (mReferrer != null) {
>             return new Uri.Builder().scheme("android-app").authority(mReferrer).build();
>         }
>         return null;
>     }

So there's no null check anywhere in regards to Activity having or not having an Intent.

The change that needs to be added to the Branch.java class is to be made inside the init() method.

From:

> if (activity != null && ActivityCompat.getReferrer(activity) != null) {
>                 PrefHelper.getInstance(activity).setInitialReferrer(ActivityCompat.getReferrer(activity).toString());
>             }
> 

To:

> if (activity != null && intent != null && ActivityCompat.getReferrer(activity) != null) {
>                 PrefHelper.getInstance(activity).setInitialReferrer(ActivityCompat.getReferrer(activity).toString());
>             }

Since this crash is constant, all newer Branch SDKs starting with 5.0.10 when the referral was introduced are crashing.
The only solution for now is downgrading to 5.0.9 or importing the SDK and doing the changes locally in the current project.

Please add the intent null check so we can resume using the latest SDKs.

Thank you very much!

**Comment by cdomingopuig** [comment]
I'm having the same issue.

**Comment by msiddiq-branch** [comment]
This has been resolved in [5.0.11](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/releases/tag/5.0.11)

**Comment by mihaicristianpetrescu** [comment]
@msiddiq-branch In 5.0.11 this activity != null was added here, but just that:

> if (activity != null && ActivityCompat.getReferrer(activity) != null) {
> PrefHelper.getInstance(activity).setInitialReferrer(ActivityCompat.getReferrer(activity).toString());
> }

However this is not the crash I was talking about.
We need an extra null check inserted there because of what **ActivityCompat.getReferrer(activity)** is doing behind the scenes.
We need it to be like this:

> if (activity != null && intent != null && ActivityCompat.getReferrer(activity) != null) {
> PrefHelper.getInstance(activity).setInitialReferrer(ActivityCompat.getReferrer(activity).toString());
> }

So this is not fixed and it should be opened and fixed properly.

Just open up an app that has the SDK integrated + another one, and then from the multi task tap on the app with the SDK integrated, it will crash.

Thank you!

**Comment by gdeluna-branch** [comment]
The fix was merged, should be released in the update next week. Thanks

**Comment by gdeluna-branch** [comment]
Released here:

https://search.maven.org/artifact/io.branch.sdk.android/library/5.1.1/aar
https://github.com/BranchMetrics/android-branch-deep-linking-attribution/releases/tag/5.1.1

Thanks

**Comment by mihaicristianpetrescu** [comment]
Confirmed, the requested solution has been applied to the codebase. Thank you!
